name: Check Test Linter

on:
  workflow_run:
    workflows:
      - Tests
    types:
      - completed

jobs:
  check_test_linter:
    name: Check Test Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Execute Script
        run: |
          python linter.py test_linter.py